import { errorResponse } from "@/lib/api-error";
import { noStore } from "@/lib/http";
import { requireAccountSubject } from "@/lib/agent/account-subject";
import { addAttachment, listAttachments, removeAttachment } from "@/lib/battle/extended-repository";
import { asRecord, asText, isStorageReference, isUuid } from "@/lib/battle/input";

type Context = { params: Promise<{ id:string }> };
const targetTypes=["battle","fact","node","move","action","review"] as const;

export async function GET(request:Request,context:Context){try{const id=(await context.params).id;if(!isUuid(id))return noStore({error:"战局标识无效。"},{status:400});const value=await listAttachments(await requireAccountSubject(request),id);return value===null?noStore({error:"战局不存在。"},{status:404}):noStore({attachments:value});}catch(error){return errorResponse(error,"读取证据附件失败。");}}
export async function POST(request:Request,context:Context){try{const id=(await context.params).id;if(!isUuid(id))return noStore({error:"战局标识无效。"},{status:400});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const targetType=body?.targetType;const filename=asText(body?.filename,255);const mediaType=asText(body?.mediaType,128);const storageKey=asText(body?.storageKey,512);const byteSize=body?.byteSize;const checksum=body?.checksum===null||body?.checksum===undefined?null:asText(body.checksum,128);if(typeof targetType!=="string"||!targetTypes.includes(targetType as never)||!filename||!mediaType||!storageKey||!isStorageReference(storageKey)||typeof byteSize!=="number"||!Number.isSafeInteger(byteSize)||byteSize<0||checksum===null&&body?.checksum!==null&&body?.checksum!==undefined||body?.targetId!==undefined&&body?.targetId!==null&&!isUuid(body.targetId)||targetType!=="battle"&&!isUuid(body?.targetId))return noStore({error:"附件元数据无效；当前只接受 HTTPS 或受控对象存储引用，不上传二进制。"},{status:400});const value=await addAttachment(await requireAccountSubject(request),id,{targetType:targetType as never,targetId:(body?.targetId as string|null|undefined)??null,filename,mediaType,storageKey,byteSize,checksum,source:asRecord(body?.source)??{}});return value===null?noStore({error:"只有战局所有者可登记证据附件。"},{status:403}):noStore({attachment:value},{status:201});}catch(error){return errorResponse(error,"登记证据附件失败。");}}
export async function DELETE(request:Request,context:Context){try{const id=(await context.params).id;const attachmentId=new URL(request.url).searchParams.get("attachmentId");if(!isUuid(id)||!isUuid(attachmentId))return noStore({error:"标识无效。"},{status:400});const value=await removeAttachment(await requireAccountSubject(request),id,attachmentId);return value===null?noStore({error:"只有战局所有者可删除证据附件。"},{status:403}):value?noStore({ok:true}):noStore({error:"附件不存在。"},{status:404});}catch(error){return errorResponse(error,"删除证据附件失败。");}}
