import { NextResponse } from "next/server";
import { AccountSubjectError, requireAccountSubject } from "@/lib/agent/account-subject";
import { asDate, asRecord, asText, isUuid } from "@/lib/battle/input";
import { getExecutionPlan, saveExecutionPlan, triggerBreaker, updateExecutionAction } from "@/lib/battle/repository";
type Context = { params: Promise<{id:string;moveId:string}> };
const breakerKinds=["cash","time","relationship","energy","legal","assumption","opportunity"];
const actionStatuses=["pending","in_progress","waiting","done","failed","skipped"];
export async function GET(request: Request, context: Context) { try { const {id:battleId,moveId}=await context.params; if(!isUuid(battleId)||!isUuid(moveId)) return NextResponse.json({error:"战局或策略标识无效。"},{status:400}); const value=await getExecutionPlan(await requireAccountSubject(request),battleId,moveId); return value===null?NextResponse.json({error:"策略不属于当前战局。"},{status:404}):NextResponse.json(value); } catch(error) { return error instanceof AccountSubjectError?NextResponse.json({error:error.message},{status:error.status}):NextResponse.json({error:"读取执行台失败。"},{status:500}); } }
export async function PUT(request: Request, context: Context) { try { const {id:battleId,moveId}=await context.params; if(!isUuid(battleId)||!isUuid(moveId)) return NextResponse.json({error:"战局或策略标识无效。"},{status:400}); const body=await request.json().catch(()=>null) as {actions?:unknown;breakers?:unknown}|null; if(!Array.isArray(body?.actions)||body.actions.length<1||body.actions.length>20||!Array.isArray(body?.breakers)||body.breakers.length<1||body.breakers.length>8) return NextResponse.json({error:"落子令必须有 1–20 项行动和 1–8 个断路器。"},{status:400}); const actions=body.actions.map((value)=>{const item=value as Record<string,unknown>;return {title:asText(item.title,240),description:asText(item.description,6000,false),owner:asText(item.owner,160,false),dueAt:asDate(item.dueAt),successSignal:asText(item.successSignal,6000,false),failureSignal:asText(item.failureSignal,6000,false)}}); const breakers=body.breakers.map((value)=>{const item=value as Record<string,unknown>;return {kind:item.kind,label:asText(item.label,200),threshold:asRecord(item.threshold),actionOnTrigger:asText(item.actionOnTrigger,6000),enabled:item.enabled!==false}}); if(actions.some((item)=>!item.title||item.dueAt===undefined)||breakers.some((item)=>!breakerKinds.includes(String(item.kind))||!item.label||!item.threshold||!item.actionOnTrigger)) return NextResponse.json({error:"行动或断路器字段无效。"},{status:400}); const result=await saveExecutionPlan(await requireAccountSubject(request),battleId,moveId,actions as Parameters<typeof saveExecutionPlan>[3],breakers as Parameters<typeof saveExecutionPlan>[4]); return result?NextResponse.json(result):NextResponse.json({error:"策略不属于当前战局。"},{status:404}); } catch(error){ return error instanceof AccountSubjectError?NextResponse.json({error:error.message},{status:error.status}):NextResponse.json({error:"保存落子执行台失败。"},{status:500}); } }
export async function PATCH(request: Request, context: Context) { try { const {id:battleId,moveId}=await context.params; if(!isUuid(battleId)||!isUuid(moveId)) return NextResponse.json({error:"战局或策略标识无效。"},{status:400}); const body=await request.json().catch(()=>null) as {actionId?:unknown;breakerId?:unknown;status?:unknown;actualCost?:unknown;action?:unknown}|null; const subject=await requireAccountSubject(request); if(body?.action==="trigger_breaker"){if(!isUuid(body.breakerId))return NextResponse.json({error:"断路器标识无效。"},{status:400});const breaker=await triggerBreaker(subject,battleId,moveId,body.breakerId);return breaker===null?NextResponse.json({error:"断路器不属于当前策略。"},{status:404}):NextResponse.json({breaker});} if(!isUuid(body?.actionId)||typeof body?.status!=="string"||!actionStatuses.includes(body.status)) return NextResponse.json({error:"行动状态无效。"},{status:400}); const actualCost=asRecord(body.actualCost)??{}; const result=await updateExecutionAction(subject,battleId,moveId,body.actionId,body.status,actualCost); return result===null?NextResponse.json({error:"行动不属于当前策略。"},{status:404}):NextResponse.json({action:result}); } catch(error){ return error instanceof AccountSubjectError?NextResponse.json({error:error.message},{status:error.status}):NextResponse.json({error:"更新行动状态失败。"},{status:500}); } }
