import { errorResponse } from "@/lib/api-error";
import { noStore } from "@/lib/http";
import { requireAccountSubject } from "@/lib/agent/account-subject";
import { asDate, asRecord, asText, isUuid } from "@/lib/battle/input";
import { listOpportunities, replaceOpportunities } from "@/lib/battle/extended-repository";
type Context = { params: Promise<{ id: string }> };
const statuses=["open","watching","acted","missed","closed"];
export async function GET(request:Request,context:Context){try{const id=(await context.params).id;if(!isUuid(id))return noStore({error:"战局标识无效。"},{status:400});const value=await listOpportunities(await requireAccountSubject(request),id);return value===null?noStore({error:"战局不存在。"},{status:404}):noStore({opportunities:value});}catch(error){return errorResponse(error, "读取机会雷达失败。");}}
export async function PUT(request:Request,context:Context){try{const id=(await context.params).id;if(!isUuid(id))return noStore({error:"战局标识无效。"},{status:400});const body=await request.json().catch(()=>null) as {opportunities?:unknown}|null;if(!Array.isArray(body?.opportunities)||body.opportunities.length>100)return noStore({error:"机会列表无效。"},{status:400});const items=body.opportunities.map((v)=>{const x=v as Record<string,unknown>;return{id:x.id===undefined?undefined:x.id,title:asText(x.title,200),description:asText(x.description,12000,false),source:asRecord(x.source)??{},opensAt:asDate(x.opensAt),bestActionAt:asDate(x.bestActionAt),closesAt:asDate(x.closesAt),decay:asRecord(x.decay)??{},status:x.status??"open"};});if(items.some((x)=>(x.id!==undefined&&!isUuid(x.id))||!x.title||x.description===null||!statuses.includes(String(x.status))||x.opensAt===undefined||x.bestActionAt===undefined||x.closesAt===undefined))return noStore({error:"机会字段无效。"},{status:400});const value=await replaceOpportunities(await requireAccountSubject(request),id,items as never);return value===null?noStore({error:"战局不存在。"},{status:404}):noStore({opportunities:value});}catch(error){return errorResponse(error, "保存机会失败。");}}
