import { NextResponse } from "next/server";
import { AccountSubjectError, requireAccountSubject } from "@/lib/agent/account-subject";
import { asDate, asRecord, asText, isUuid, isIn } from "@/lib/battle/input";
import { addTimeline, BattleIntegrityError, listTimeline } from "@/lib/battle/extended-repository";
import { JUNCTION_KINDS, TIMELINE_RELATIONS } from "@/lib/battle/types";
type Context = { params: Promise<{ id: string }> };
const truth = ["observed","assumed","projected","verified","rejected"] as const;
export async function GET(request: Request, context: Context) { try { const id=(await context.params).id; if(!isUuid(id)) return NextResponse.json({error:"战局标识无效。"},{status:400}); const value=await listTimeline(await requireAccountSubject(request),id); return value===null?NextResponse.json({error:"战局不存在。"},{status:404}):NextResponse.json(value); } catch(error){ return error instanceof AccountSubjectError?NextResponse.json({error:error.message},{status:error.status}):NextResponse.json({error:"读取时间线失败。"},{status:500}); } }
export async function POST(request: Request, context: Context) { try { const id=(await context.params).id; if(!isUuid(id)) return NextResponse.json({error:"战局标识无效。"},{status:400}); const body=await request.json().catch(()=>null) as {nodes?:unknown;edges?:unknown}|null; if(!Array.isArray(body?.nodes)||!Array.isArray(body?.edges)||body.nodes.length>200||body.edges.length>500) return NextResponse.json({error:"时间线数据无效。"},{status:400}); const nodes=body.nodes.map((v)=>{const x=v as Record<string,unknown>;return {kind:x.kind,title:asText(x.title,200),description:asText(x.description,12000,false),startsAt:asDate(x.startsAt),endsAt:asDate(x.endsAt),truthStatus:x.truthStatus,importance:typeof x.importance==="number"?Math.max(1,Math.min(5,x.importance)):3,source:asRecord(x.source)??{}}}); const edges=body.edges.map((v)=>{const x=v as Record<string,unknown>;return {fromNodeId:x.fromNodeId,toNodeId:x.toNodeId,relation:x.relation,confidence:typeof x.confidence==="number"?Math.max(0,Math.min(100,x.confidence)):50,evidence:asRecord(x.evidence)??{}}}); if(nodes.some((x)=>!isIn(x.kind,JUNCTION_KINDS)||!x.title||x.description===null||!isIn(x.truthStatus,truth)||x.source.layer==="ai"&&["observed","verified"].includes(String(x.truthStatus))) || edges.some((x)=>!isUuid(x.fromNodeId)||!isUuid(x.toNodeId)||x.fromNodeId===x.toNodeId||!isIn(x.relation,TIMELINE_RELATIONS))) return NextResponse.json({error:"节点或连线字段无效；AI 推演不能直接成为已观察事实。"},{status:400}); const value=await addTimeline(await requireAccountSubject(request),id,nodes as never,edges as never); return value===null?NextResponse.json({error:"战局不存在。"},{status:404}):NextResponse.json(value,{status:201}); } catch(error){ return error instanceof AccountSubjectError?NextResponse.json({error:error.message},{status:error.status}):error instanceof BattleIntegrityError?NextResponse.json({error:error.message},{status:400}):NextResponse.json({error:"写入时间线失败。"},{status:500}); } }
