"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { BattleAdvice, BattleAttachment } from "@/lib/battle/types";

type Props = { accessToken?:string; canPersist:boolean; battleId:string|null };
const jsonHeaders=(token?:string)=>({Authorization:`Bearer ${token??""}`,"Content-Type":"application/json"});

export function BattleCollaborationPanel({accessToken,canPersist,battleId}:Props){
  const [advice,setAdvice]=useState<BattleAdvice[]>([]); const [attachments,setAttachments]=useState<BattleAttachment[]>([]); const [opinion,setOpinion]=useState(""); const [rationale,setRationale]=useState(""); const [uncertainty,setUncertainty]=useState(""); const [link,setLink]=useState({filename:"",storageKey:"",mediaType:"text/uri-list",byteSize:"0",checksum:""}); const [status,setStatus]=useState("");
  const headers=useMemo(()=>jsonHeaders(accessToken),[accessToken]);
  const request=useCallback(async(url:string,init:RequestInit={})=>{const response=await fetch(url,{...init,headers:{...headers,...(init.headers??{})},cache:"no-store"});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error((data as {error?:string}).error||"请求失败");return data as Record<string,unknown>;},[headers]);
  const load=useCallback(async()=>{if(!canPersist||!accessToken||!battleId)return;try{const [a,e]=await Promise.all([request(`/api/battles/${battleId}/advice`),request(`/api/battles/${battleId}/attachments`)]);setAdvice((a.advice as BattleAdvice[])??[]);setAttachments((e.attachments as BattleAttachment[])??[]);}catch(error){setStatus(error instanceof Error?error.message:"读取协作层失败");}},[battleId,canPersist,accessToken,request]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const submitAdvice=async()=>{if(!battleId||!opinion.trim())return;try{await request(`/api/battles/${battleId}/advice`,{method:"POST",body:JSON.stringify({targetType:"battle",opinion,rationale,uncertainty,source:{source:"user"}})});setOpinion("");setRationale("");setUncertainty("");setStatus("顾问意见已入账；它不会自动变成事实或行动。 ");await load();}catch(error){setStatus(error instanceof Error?error.message:"提交意见失败");}};
  const adopt=async(id:string,adoptedAs:"fact"|"action"|"reference")=>{if(!battleId)return;try{await request(`/api/battles/${battleId}/advice`,{method:"PATCH",body:JSON.stringify({adviceId:id,action:"adopt",adoptedAs})});setStatus(`已明确采纳为${adoptedAs === "fact" ? "事实（待核验）" : adoptedAs === "action" ? "未来行动" : "参考"}。`);await load();}catch(error){setStatus(error instanceof Error?error.message:"采纳意见失败");}};
  const addEvidence=async()=>{if(!battleId||!link.filename.trim()||!link.storageKey.trim())return;try{await request(`/api/battles/${battleId}/attachments`,{method:"POST",body:JSON.stringify({...link,byteSize:Number(link.byteSize),checksum:link.checksum||null,targetType:"battle",targetId:null,source:{source:"user",storageMode:"external_metadata_only"}})});setLink({filename:"",storageKey:"",mediaType:"text/uri-list",byteSize:"0",checksum:""});setStatus("证据链接已登记；二进制仍由外部对象存储负责。 ");await load();}catch(error){setStatus(error instanceof Error?error.message:"登记证据失败");}};
  if(!canPersist)return <section className="battle-collaboration"><strong>协作与证据层</strong><span>登录后才能保存顾问意见和证据引用。</span></section>;
  if(!battleId)return <section className="battle-collaboration"><strong>协作与证据层</strong><span>建立或打开战局后，这里才会关联顾问意见与证据。</span></section>;
  return <section className="battle-collaboration"><header><div><span>SEPARATE LAYERS</span><h3>协作意见 · 证据引用</h3><p>事实、AI 推演、顾问意见三层分开。所有者采纳前，意见不会改变战局事实。</p></div></header><div className="battle-collaboration__grid"><article><h4>顾问意见</h4>{advice.length?advice.slice(0,8).map(item=><div className={`battle-collaboration__opinion is-${item.status}`} key={item.id}><b>{item.status === "proposed"?"待所有者处理":item.status}</b><p>{item.opinion}</p>{item.rationale&&<small>依据：{item.rationale}</small>}{item.uncertainty&&<small>不确定：{item.uncertainty}</small>}{item.status==="proposed"&&<div><button type="button" onClick={()=>void adopt(item.id,"fact")}>采纳为事实</button><button type="button" onClick={()=>void adopt(item.id,"action")}>采纳为行动</button><button type="button" onClick={()=>void adopt(item.id,"reference")}>仅作参考</button></div>}</div>):<p>暂无顾问意见。</p>}<div className="battle-collaboration__form"><textarea value={opinion} onChange={e=>setOpinion(e.target.value)} placeholder="提交一条可审查的意见"/><input value={rationale} onChange={e=>setRationale(e.target.value)} placeholder="依据（可选）"/><input value={uncertainty} onChange={e=>setUncertainty(e.target.value)} placeholder="不确定性（可选）"/><button type="button" onClick={()=>void submitAdvice()}>提交意见</button></div></article><article><h4>证据引用（元数据）</h4><p className="battle-collaboration__note">当前登记外部 HTTPS / 对象存储引用，不把二进制塞进产品数据库。</p>{attachments.length?attachments.slice(0,8).map(item=><div className="battle-collaboration__evidence" key={item.id}><b>{item.filename}</b><a href={item.storageKey} target="_blank" rel="noreferrer">打开引用</a><small>{item.mediaType} · {item.byteSize} bytes</small></div>):<p>暂无证据引用。</p>}<div className="battle-collaboration__form"><input value={link.filename} onChange={e=>setLink({...link,filename:e.target.value})} placeholder="文件名"/><input value={link.storageKey} onChange={e=>setLink({...link,storageKey:e.target.value})} placeholder="受控 HTTPS 链接或存储 key"/><input value={link.mediaType} onChange={e=>setLink({...link,mediaType:e.target.value})} placeholder="媒体类型"/><input inputMode="numeric" value={link.byteSize} onChange={e=>setLink({...link,byteSize:e.target.value})} placeholder="字节数"/><button type="button" onClick={()=>void addEvidence()}>登记引用</button></div></article></div>{status&&<footer>{status}</footer>}</section>;
}
