"use client";

import { AlertTriangle, Crosshair, Database, Download, Lock, MessageCircle, Radar, Send, ShieldAlert, SkipForward, Target, TimerReset } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { Battle, BattleConstraint, BattleFact, GravityLine, InventoryItem, Junction, Move, Opportunity, OppositionScan, ResourceSnapshot, TimelineEdge, TimelineNode } from "@/lib/battle/types";
import { buildDefaultGravityLine, buildMoveTemplates, detectJunctions } from "@/lib/battle/rules";
import { BattleStrategyArchive } from "./battle-strategy-archive";
import { BattleCollaborationPanel } from "./battle-collaboration-panel";
import { BattleCopilotPanel } from "./battle-copilot-panel";

type Props = { accessToken?: string; canPersist: boolean; guestCheckoutToken?: string; guestUsageAvailable?: number; accountUsageAvailable?: number; onLogin: () => void; onOpenWorkbench: () => void };
type Draft = { title:string; objective:string; minimumOutcome:string; idealOutcome:string; opponentSummary:string; hardDeadline:string };
type Action = { id?:string; title:string; description:string; owner:string; dueAt:string|null; successSignal:string; failureSignal:string; status?:string; actualCost?:Record<string,unknown> };
type Breaker = { id?:string; kind:string; label:string; threshold:Record<string,unknown>; actionOnTrigger:string; enabled:boolean; triggeredAt?:string|null };
type ResourceFields = { cashAvailable:string; monthlyFixedCost:string; monthlyNetCashflow:string; weeklyHoursAvailable:string; weeklyHoursCommitted:string; consecutiveHighPressureDays:string; maxHighPressureDays:string };
const emptyDraft:Draft = { title:"",objective:"",minimumOutcome:"",idealOutcome:"",opponentSummary:"",hardDeadline:"" };
const headers=(token?:string)=>({Authorization:`Bearer ${token??""}`,"Content-Type":"application/json"});
const numeric=(value:string)=>value.trim()===""?undefined:Number(value);
const localId=(prefix:string)=>`${prefix}-${typeof crypto!=="undefined"&&"randomUUID" in crypto?crypto.randomUUID():Math.random().toString(36).slice(2)}`;

export function BattleCommandCenter({accessToken,canPersist,guestCheckoutToken,guestUsageAvailable,accountUsageAvailable,onLogin,onOpenWorkbench}:Props) {
  const [battles,setBattles]=useState<Battle[]>([]); const [battle,setBattle]=useState<Battle|null>(null); const [draft,setDraft]=useState<Draft>(emptyDraft);
  const [facts,setFacts]=useState<BattleFact[]>([]); const [factText,setFactText]=useState(""); const [factKind,setFactKind]=useState<BattleFact["kind"]>("fact"); const [factSource,setFactSource]=useState<BattleFact["source"]>("user"); const [factConfidence,setFactConfidence]=useState("100"); const [factOccurredAt,setFactOccurredAt]=useState(""); const [factVerifiedAt,setFactVerifiedAt]=useState(""); const [constraints,setConstraints]=useState<BattleConstraint[]>([]); const [inventory,setInventory]=useState<InventoryItem[]>([]);
  const [resources,setResources]=useState<ResourceFields>({cashAvailable:"",monthlyFixedCost:"",monthlyNetCashflow:"",weeklyHoursAvailable:"",weeklyHoursCommitted:"",consecutiveHighPressureDays:"",maxHighPressureDays:""}); const [resourceSnapshot,setResourceSnapshot]=useState<ResourceSnapshot>({});
  const [gravity,setGravity]=useState<GravityLine|null>(null); const [junctions,setJunctions]=useState<Junction[]>([]); const [moves,setMoves]=useState<Move[]>([]); const [selectedJunction,setSelectedJunction]=useState<Junction|null>(null); const [selectedMove,setSelectedMove]=useState<Move|null>(null); const [execution,setExecution]=useState<{actions:Action[];breakers:Breaker[]}|null>(null);
  const [timeline,setTimeline]=useState<TimelineNode[]>([]); const [timelineEdges,setTimelineEdges]=useState<TimelineEdge[]>([]); const [timelineDraft,setTimelineDraft]=useState({title:"",startsAt:"",kind:"fact",truthStatus:"observed"}); const [opportunities,setOpportunities]=useState<Opportunity[]>([]); const [opportunityDraft,setOpportunityDraft]=useState({title:"",description:"",bestActionAt:"",closesAt:"",decayReason:"",missedCost:""});
  const [reviews,setReviews]=useState<Array<{id:string;outcome:string;nextAdjustment:string}>>([]); const [reviewDraft,setReviewDraft]=useState({outcome:"",facts:"",whatChanged:"",nextAdjustment:""}); const [status,setStatus]=useState("等待开局"); const [busy,setBusy]=useState(false);
  const auth=useMemo(()=>headers(accessToken),[accessToken]);
  const isGuest=!canPersist;
  const request=useCallback(async(url:string,init:RequestInit={})=>{const response=await fetch(url,{...init,headers:{...auth,...(init.headers??{})},cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"请求失败");return body as Record<string,unknown>;},[auth]);

  const loadBattle=useCallback(async(value:Battle)=>{
    setBattle(value);setDraft({title:value.title,objective:value.objective,minimumOutcome:value.minimumOutcome,idealOutcome:value.idealOutcome,opponentSummary:value.opponentSummary,hardDeadline:value.hardDeadline?.slice(0,16)??""});
    if(!canPersist)return;
    try { const [f,m,c,i,r,co,t,o,rv,a]=await Promise.all([request(`/api/battles/${value.id}/facts`),request(`/api/battles/${value.id}/moves`),request(`/api/battles/${value.id}/constraints`),request(`/api/battles/${value.id}/inventory`),request(`/api/battles/${value.id}/resources`),request(`/api/battles/${value.id}/commitments`),request(`/api/battles/${value.id}/timeline`),request(`/api/battles/${value.id}/opportunities`),request(`/api/battles/${value.id}/reviews`),request(`/api/battles/${value.id}/analysis`)]); const loadedMoves=(m.moves as Move[])??[];const loadedJunctions=(a.junctions as Junction[])??[];const snapshot=(r.snapshot as ResourceSnapshot|null)??{};const commitment=co.commitment as {moveId?:string}|null;const move=commitment?.moveId?loadedMoves.find((row)=>row.id===commitment.moveId)??null:null;const activeJunction=move?.junctionId?loadedJunctions.find((row)=>row.id===move.junctionId)??loadedJunctions[0]??null:loadedJunctions[0]??null;setFacts((f.facts as BattleFact[])??[]);setGravity((a.gravity as GravityLine|null)??null);setJunctions(loadedJunctions);setSelectedJunction(activeJunction);setMoves(activeJunction?loadedMoves.filter((row)=>row.junctionId===activeJunction.id):loadedMoves);setConstraints((c.constraints as BattleConstraint[])??[]);setInventory((i.inventory as InventoryItem[])??[]);setResourceSnapshot(snapshot);setTimeline((t.nodes as TimelineNode[])??[]);setTimelineEdges((t.edges as TimelineEdge[])??[]);setOpportunities((o.opportunities as Opportunity[])??[]);setReviews((rv.reviews as Array<{id:string;outcome:string;nextAdjustment:string}>)??[]);setResources({cashAvailable:String(snapshot.cashAvailable??""),monthlyFixedCost:String(snapshot.monthlyFixedCost??""),monthlyNetCashflow:String(snapshot.monthlyNetCashflow??""),weeklyHoursAvailable:String(snapshot.weeklyHoursAvailable??""),weeklyHoursCommitted:String(snapshot.weeklyHoursCommitted??""),consecutiveHighPressureDays:String(snapshot.consecutiveHighPressureDays??""),maxHighPressureDays:String(snapshot.maxHighPressureDays??"")});setSelectedMove(move);if(move){const plan=await request(`/api/battles/${value.id}/moves/${move.id}/execution`);setExecution({actions:(plan.actions as Action[])??[],breakers:(plan.breakers as Breaker[])??[]});}else setExecution(null); } catch(error){setStatus(error instanceof Error?error.message:"读取战局失败");}
  },[canPersist,request]);
  useEffect(()=>{if(!canPersist||!accessToken)return;void request("/api/battles").then((data)=>{const list=(data.battles as Battle[])??[];setBattles(list);if(list[0])void loadBattle(list[0]);}).catch((error)=>setStatus(error instanceof Error?error.message:"读取战局失败"));},[accessToken,canPersist,loadBattle,request]);
  const create=async()=>{if(!draft.title.trim()||!draft.objective.trim()){setStatus("先写清这一局要赢什么。");return;}if(!canPersist){const now=new Date().toISOString();const value:Battle={id:localId("guest-battle"),title:draft.title.trim(),objective:draft.objective.trim(),minimumOutcome:draft.minimumOutcome.trim(),idealOutcome:draft.idealOutcome.trim(),opponentSummary:draft.opponentSummary.trim(),hardDeadline:draft.hardDeadline?new Date(draft.hardDeadline).toISOString():null,status:"intake",createdAt:now,updatedAt:now};setBattles([value]);setBattle(value);setStatus("访客演练已建立：数据只在当前标签页内存中，刷新、关闭或换设备会丢失。");return;}setBusy(true);try{const data=await request("/api/battles",{method:"POST",body:JSON.stringify({...draft,hardDeadline:draft.hardDeadline?new Date(draft.hardDeadline).toISOString():null})});const value=data.battle as Battle;setBattles((rows)=>[value,...rows]);await loadBattle(value);setStatus("战局已建立：先盘点底牌，再找交叉点。");}catch(error){setStatus(error instanceof Error?error.message:"开局失败");}finally{setBusy(false);}};
  const addFact=async()=>{if(!battle||!factText.trim())return;const confidence=Number(factConfidence);if(!Number.isFinite(confidence)||confidence<0||confidence>100){setStatus("置信度必须是 0–100。");return;}const input={kind:factKind,content:factText.trim(),source:factSource,confidence,occurredAt:factOccurredAt?new Date(factOccurredAt).toISOString():null,verifiedAt:factVerifiedAt?new Date(factVerifiedAt).toISOString():null};if(isGuest){setFacts((rows)=>[...rows,{...input,id:localId("guest-fact"),battleId:battle.id,createdAt:new Date().toISOString()}]);setFactText("");setStatus("访客演练输入已分层记录；登录后可永久保存。");return;}setBusy(true);try{const data=await request(`/api/battles/${battle.id}/facts`,{method:"POST",body:JSON.stringify({facts:[input]})});setFacts((rows)=>[...rows,...((data.facts as BattleFact[])??[])]);setFactText("");setFactKind("fact");setFactSource("user");setFactConfidence("100");setFactOccurredAt("");setFactVerifiedAt("");setStatus(factKind==="fact"?"现实事实已入账。":"分层记录已入账，不会被当作已验证事实。");}catch(error){setStatus(error instanceof Error?error.message:"事实写入失败");}finally{setBusy(false);}};
  const saveResources=async()=>{if(!battle)return;const snapshot:ResourceSnapshot={cashAvailable:numeric(resources.cashAvailable),monthlyFixedCost:numeric(resources.monthlyFixedCost),monthlyNetCashflow:numeric(resources.monthlyNetCashflow),weeklyHoursAvailable:numeric(resources.weeklyHoursAvailable),weeklyHoursCommitted:numeric(resources.weeklyHoursCommitted),consecutiveHighPressureDays:numeric(resources.consecutiveHighPressureDays),maxHighPressureDays:numeric(resources.maxHighPressureDays)};if(isGuest){setResourceSnapshot(snapshot);setStatus("访客演练资源快照已锁定于当前标签页。");return;}setBusy(true);try{const data=await request(`/api/battles/${battle.id}/resources`,{method:"PUT",body:JSON.stringify({snapshot})});setResourceSnapshot((data.snapshot as ResourceSnapshot)??snapshot);setStatus("资源快照已锁定版本。");}catch(error){setStatus(error instanceof Error?error.message:"资源保存失败");}finally{setBusy(false);}};
  const saveInventory=async()=>{if(!battle)return;if(isGuest){setStatus("访客演练的硬约束与底牌已记在当前标签页；扫描不会绕过红线。");return;}setBusy(true);try{await Promise.all([request(`/api/battles/${battle.id}/constraints`,{method:"PUT",body:JSON.stringify({constraints})}),request(`/api/battles/${battle.id}/inventory`,{method:"PUT",body:JSON.stringify({inventory})})]);setStatus("硬约束与底牌已保存；扫描不会绕过红线。");}catch(error){setStatus(error instanceof Error?error.message:"底牌保存失败");}finally{setBusy(false);}};
  const generate=async()=>{if(!battle)return;if(isGuest){const input={objective:battle.objective,minimumOutcome:battle.minimumOutcome,idealOutcome:battle.idealOutcome,opponentSummary:battle.opponentSummary,hardDeadline:battle.hardDeadline,facts,constraints,inventory,resourceSnapshot};const next=detectJunctions(input).map((junction)=>({...junction,id:localId("guest-junction"),battleId:battle.id}));const gravityLine=buildDefaultGravityLine(input);const generated=next.flatMap((junction,junctionIndex)=>buildMoveTemplates(input,gravityLine,junction).map((move,index)=>({...move,id:localId("guest-move"),battleId:battle.id,junctionId:junction.id,version:junctionIndex+1,state:"draft" as const,source:{...move.source,guestEphemeral:true,index}})));const primary=next[0]??null;setGravity(gravityLine);setJunctions(next);setMoves(primary?generated.filter((move)=>move.junctionId===primary.id):[]);setSelectedJunction(primary);setStatus("访客演练已为每个交叉点生成重力线、对手盘和三手策略；登录后可保存为正式战局。");return;}setBusy(true);try{const data=await request(`/api/battles/${battle.id}/analysis`,{method:"POST",body:"{}"});const next=(data.junctions as Junction[])??[];const allMoves=(data.moves as Move[])??[];const primary=next[0]??null;setGravity((data.gravity as GravityLine|null)??null);setJunctions(next);setMoves(primary?allMoves.filter((move)=>move.junctionId===primary.id):[]);setSelectedJunction(primary);setStatus("重力线、对手盘扫描与现实交叉点已生成。");}catch(error){setStatus(error instanceof Error?error.message:"推演失败");}finally{setBusy(false);}};
  const choose=async(junction:Junction)=>{if(!battle)return;setSelectedJunction(junction);if(isGuest){const input={objective:battle.objective,minimumOutcome:battle.minimumOutcome,idealOutcome:battle.idealOutcome,opponentSummary:battle.opponentSummary,hardDeadline:battle.hardDeadline,facts,constraints,inventory,resourceSnapshot};const guestMoves=buildMoveTemplates(input,gravity??buildDefaultGravityLine(input),junction).map((move,index)=>({...move,id:localId("guest-move"),battleId:battle.id,junctionId:junction.id,version:1,state:"draft" as const,source:{...move.source,guestEphemeral:true,index}}));setMoves(guestMoves);return;}try{const data=await request(`/api/battles/${battle.id}/moves?junctionId=${junction.id}`);setMoves((data.moves as Move[])??[]);}catch(error){setStatus(error instanceof Error?error.message:"读取策略失败");}};
  const commit=async(move:Move)=>{if(!battle)return;const changeReason=selectedMove?(window.prompt("这是换线。请记录为什么改变策略：")??""):undefined;if(selectedMove&&!(changeReason??"").trim()){setStatus("换线必须留下变化原因。");return;}if(isGuest){setSelectedMove({...move,state:"selected"});setExecution(null);setStatus("访客演练已落子：执行状态只保存在当前标签页，登录后才能生成可追溯正式版本。");return;}setBusy(true);try{const data=await request(`/api/battles/${battle.id}/commitments`,{method:"POST",body:JSON.stringify({moveId:move.id,changeReason})});setSelectedMove(move);setExecution(null);setStatus(`已落子 V${(data.commitment as {version:number}).version}：现在进入执行。`);}catch(error){setStatus(error instanceof Error?error.message:"落子失败");}finally{setBusy(false);}};
  const prepareExecution=()=>{if(!selectedMove)return;setExecution({actions:selectedMove.actions.map((item)=>({...item,successSignal:String(selectedMove.validation.successSignal??"出现可核验正向信号"),failureSignal:String(selectedMove.stop.condition??"关键假设失效")})),breakers:[{kind:"assumption",label:"核心假设被证伪",threshold:{},actionOnTrigger:"停止当前动作，回到交叉点重新推演",enabled:true}]});};
  const saveExecution=async()=>{if(!battle||!selectedMove||!execution)return;if(isGuest){setExecution({actions:execution.actions.map((action)=>({...action,id:action.id??localId("guest-action")})),breakers:execution.breakers.map((breaker)=>({...breaker,id:breaker.id??localId("guest-breaker")}))});setStatus("访客演练落子令已保存于当前标签页。登录后可锁定正式版本。");return;}setBusy(true);try{const data=await request(`/api/battles/${battle.id}/moves/${selectedMove.id}/execution`,{method:"PUT",body:JSON.stringify(execution)});setExecution({actions:(data.actions as Action[])??[],breakers:(data.breakers as Breaker[])??[]});setStatus("落子令已保存：行动、期限和断路器同时生效。");}catch(error){setStatus(error instanceof Error?error.message:"执行台保存失败");}finally{setBusy(false);}};
  const updateAction=async(action:Action)=>{if(!battle||!selectedMove||!action.id||!action.status)return;if(isGuest){setExecution((current)=>current?{...current,actions:current.actions.map((item)=>item.id===action.id?action:item)}:current);return;}try{await request(`/api/battles/${battle.id}/moves/${selectedMove.id}/execution`,{method:"PATCH",body:JSON.stringify({actionId:action.id,status:action.status,actualCost:action.actualCost??{}})});setExecution((current)=>current?{...current,actions:current.actions.map((item)=>item.id===action.id?action:item)}:current);}catch(error){setStatus(error instanceof Error?error.message:"行动状态更新失败");}};
  const trigger=async(breaker:Breaker)=>{if(!battle||!selectedMove||!breaker.id)return;if(isGuest){setSelectedMove(null);setExecution(null);setStatus("访客演练断路器已触发：当前落子停止，回到交叉点重新推演。");return;}setBusy(true);try{await request(`/api/battles/${battle.id}/moves/${selectedMove.id}/execution`,{method:"PATCH",body:JSON.stringify({action:"trigger_breaker",breakerId:breaker.id})});setSelectedMove(null);setExecution(null);setStatus("断路器已触发：当前落子停止，回到战局重新推演。");}catch(error){setStatus(error instanceof Error?error.message:"触发断路器失败");}finally{setBusy(false);}};
  const addTimeline=async()=>{if(!battle||!timelineDraft.title.trim())return;const input={kind:timelineDraft.kind as TimelineNode["kind"],title:timelineDraft.title,description:"",startsAt:timelineDraft.startsAt?new Date(timelineDraft.startsAt).toISOString():null,endsAt:null,truthStatus:timelineDraft.truthStatus as TimelineNode["truthStatus"],importance:3,source:{source:"user"}};if(isGuest){setTimeline((rows)=>[...rows,{...input,id:localId("guest-node"),battleId:battle.id}]);setTimelineDraft({title:"",startsAt:"",kind:"fact",truthStatus:"observed"});setStatus("访客演练时间线已入图，刷新页面会丢失。");return;}setBusy(true);try{const data=await request(`/api/battles/${battle.id}/timeline`,{method:"POST",body:JSON.stringify({nodes:[input],edges:[]})});setTimeline((rows)=>[...rows,...((data.nodes as TimelineNode[])??[])]);setTimelineDraft({title:"",startsAt:"",kind:"fact",truthStatus:"observed"});setStatus("时间线节点已入图，事实、假设与反事实保持分层。");}catch(error){setStatus(error instanceof Error?error.message:"时间线写入失败");}finally{setBusy(false);}};
  const linkTimeline=async(fromNodeId:string,toNodeId:string,relation:string)=>{if(!battle||!fromNodeId||!toNodeId||fromNodeId===toNodeId)return;const input={fromNodeId,toNodeId,relation:relation as TimelineEdge["relation"],confidence:relation==="counterfactual"?30:80,evidence:{source:"user",relationKind:relation}};if(isGuest){setTimelineEdges((rows)=>[...rows,{...input,id:localId("guest-edge"),battleId:battle.id}]);setStatus(relation==="counterfactual"?"访客演练幽灵对照线已标为假设。":"访客演练因果/依赖连线已入图。");return;}setBusy(true);try{const data=await request(`/api/battles/${battle.id}/timeline`,{method:"POST",body:JSON.stringify({nodes:[],edges:[input]})});setTimelineEdges((rows)=>[...rows,...((data.edges as TimelineEdge[])??[])]);setStatus(relation==="counterfactual"?"幽灵对照线已标为假设，不会伪装成已发生事实。":"因果/依赖连线已入图。");}catch(error){setStatus(error instanceof Error?error.message:"时间线连线失败");}finally{setBusy(false);}};
  const addOpportunity=async()=>{if(!battle||!opportunityDraft.title.trim()||!opportunityDraft.closesAt)return;const item={id:localId("guest-opportunity"),battleId:battle.id,title:opportunityDraft.title,description:opportunityDraft.description,source:{source:"user"},opensAt:null,bestActionAt:opportunityDraft.bestActionAt?new Date(opportunityDraft.bestActionAt).toISOString():null,closesAt:new Date(opportunityDraft.closesAt).toISOString(),decay:{reason:opportunityDraft.decayReason||"截止后机会关闭",missedCost:opportunityDraft.missedCost||"错过后回到默认路径"},status:"open" as const};if(isGuest){setOpportunities((rows)=>[...rows,item]);setOpportunityDraft({title:"",description:"",bestActionAt:"",closesAt:"",decayReason:"",missedCost:""});setStatus("访客演练窗口已进入雷达，刷新页面会丢失。");return;}setBusy(true);try{const data=await request(`/api/battles/${battle.id}/opportunities`,{method:"PUT",body:JSON.stringify({opportunities:[...opportunities,item]})});setOpportunities((data.opportunities as Opportunity[])??[]);setOpportunityDraft({title:"",description:"",bestActionAt:"",closesAt:"",decayReason:"",missedCost:""});setStatus("窗口已进入雷达；等待的物理代价可追踪。");}catch(error){setStatus(error instanceof Error?error.message:"机会保存失败");}finally{setBusy(false);}};
  const review=async()=>{if(!battle||!reviewDraft.outcome.trim())return;if(isGuest){setReviews((rows)=>[{id:localId("guest-review"),outcome:reviewDraft.outcome,nextAdjustment:reviewDraft.nextAdjustment},...rows]);setReviewDraft({outcome:"",facts:"",whatChanged:"",nextAdjustment:""});setStatus("访客演练复盘已记录；登录后可沉淀为可校准长期档案。");return;}setBusy(true);try{const data=await request(`/api/battles/${battle.id}/reviews`,{method:"POST",body:JSON.stringify(reviewDraft)});const value=data.review as {id:string;outcome:string;nextAdjustment:string};setReviews((rows)=>[value,...rows]);setReviewDraft({outcome:"",facts:"",whatChanged:"",nextAdjustment:""});setStatus("复盘已入档：评价的是当时判断和执行，不是事后成败。");}catch(error){setStatus(error instanceof Error?error.message:"复盘失败");}finally{setBusy(false);}};
  const exportReport=async()=>{if(!battle)return;try{if(isGuest){const text=`# ${battle.title}\n\n## 战局\n- 目标：${battle.objective}\n- 最低结果：${battle.minimumOutcome||"未填写"}\n- 理想结果：${battle.idealOutcome||"未填写"}\n\n## 访客演练提示\n本报告来自当前标签页的临时演练，未写入账户档案；登录后可形成版本化战局与完整战报。\n\n## 默认重力线\n${gravity?.summary||"尚未扫描"}\n\n## 事实\n${facts.map((fact)=>`- [${fact.kind}] ${fact.content}`).join("\n")||"- 暂无"}\n\n## 三手策略\n${moves.map((move)=>`- ${move.title}：${move.rationale}`).join("\n")||"- 暂无"}`;const blob=new Blob([text],{type:"text/markdown;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`shengtian-guest-${battle.id}.md`;link.click();URL.revokeObjectURL(url);setStatus("访客演练报告已导出；登录后可导出完整可追溯战报。");return;}const response=await fetch(`/api/battles/${battle.id}/report?format=markdown`,{headers:auth});if(!response.ok)throw new Error("导出失败");const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`shengtian-${battle.id}.md`;link.click();URL.revokeObjectURL(url);}catch(error){setStatus(error instanceof Error?error.message:"导出失败");}};
  const deleteCurrentBattle=async()=>{if(!battle||!window.confirm(isGuest?"关闭这次访客演练？当前标签页内的临时数据会丢失。":"删除后该战局及其事实、落子、附件将无法恢复。确定删除？"))return;if(isGuest){setBattles([]);reset();setStatus("访客演练已清除。");return;}setBusy(true);try{await request(`/api/battles/${battle.id}`,{method:"DELETE",body:JSON.stringify({confirmation:"DELETE"})});setBattles((rows)=>rows.filter((row)=>row.id!==battle.id));reset();setStatus("战局及其关联数据已删除。");}catch(error){setStatus(error instanceof Error?error.message:"删除战局失败");}finally{setBusy(false);}};
  const reset=()=>{setBattle(null);setDraft(emptyDraft);setFacts([]);setFactText("");setFactKind("fact");setFactSource("user");setFactConfidence("100");setFactOccurredAt("");setFactVerifiedAt("");setGravity(null);setConstraints([]);setInventory([]);setResources({cashAvailable:"",monthlyFixedCost:"",monthlyNetCashflow:"",weeklyHoursAvailable:"",weeklyHoursCommitted:"",consecutiveHighPressureDays:"",maxHighPressureDays:""});setResourceSnapshot({});setJunctions([]);setSelectedJunction(null);setMoves([]);setSelectedMove(null);setExecution(null);setTimeline([]);setTimelineEdges([]);setOpportunities([]);setOpportunityDraft({title:"",description:"",bestActionAt:"",closesAt:"",decayReason:"",missedCost:""});setReviews([]);setStatus("准备开新战局");};
  const runway=resourceSnapshot.cashAvailable!==undefined&&resourceSnapshot.monthlyFixedCost?`${Math.max(0,Math.floor(resourceSnapshot.cashAvailable/resourceSnapshot.monthlyFixedCost*30))} 天`:"未量化"; const time=resourceSnapshot.weeklyHoursAvailable!==undefined&&resourceSnapshot.weeklyHoursCommitted!==undefined?`${Math.max(0,resourceSnapshot.weeklyHoursAvailable-resourceSnapshot.weeklyHoursCommitted)} 小时/周`:"未量化";

  return <main className="battle-command" aria-label="胜天半子现实极限博弈终端">
    <header className="battle-command__header"><div><span>SHENGTIAN / REALITY WAR ROOM</span><h1>胜天半子</h1><p>天是现实重力，子是你手里仍能落下的那一步。</p></div><div className="battle-command__header-actions"><button type="button" onClick={onOpenWorkbench}>排盘叠层</button>{canPersist?<span><Database size={14}/> 已连接战局档案</span>:<button type="button" onClick={onLogin}><Lock size={14}/> 登录以保存</button>}</div></header>{isGuest?<aside className="battle-command__guest-warning" role="status"><Lock size={14}/><span>访客演练模式：可完整体验开局、扫描、三手策略、落子与复盘；数据只在当前标签页内存，刷新、关闭页面或换设备即丢失。登录后才可持久化、协作、调用推演官与导出完整档案。</span><button type="button" onClick={onLogin}>登录并保存</button></aside>:null}
    <section className="battle-command__layout"><aside className="battle-command__sidebar"><div className="battle-command__eyebrow"><Radar size={14}/> 战局列表</div>{battles.map((item)=><button key={item.id} type="button" className={battle?.id===item.id?"is-active":""} onClick={()=>void loadBattle(item)}><strong>{item.title}</strong><small>{item.status} · {item.hardDeadline?.slice(0,10)??"无硬期限"}</small></button>)}<button type="button" className="battle-command__new" onClick={reset}>＋ 开新战局</button></aside>
    <section className="battle-command__center">{!battle?<ConversationalIntake draft={draft} setDraft={setDraft} busy={busy} create={create}/>:<><div className="battle-command__battle-head"><div><span>ACTIVE BATTLE / {battle.status.toUpperCase()}</span><h2>{battle.title}</h2><p>{battle.objective}</p></div><div className="battle-command__battle-actions"><button type="button" onClick={()=>void exportReport()}><Download size={14}/> 导出战报</button><button type="button" className="battle-command__danger" disabled={busy} onClick={()=>void deleteCurrentBattle()}>删除战局</button><button type="button" className="battle-command__primary" disabled={busy} onClick={()=>void generate()}><Radar size={15}/> 扫描交叉点</button></div></div><div className="battle-command__inventory"><Metric label="硬期限" value={battle.hardDeadline?.slice(0,16).replace("T"," ")??"未量化"}/><Metric label="事实入账" value={`${facts.length} 条`}/><Metric label="现金跑道" value={runway}/><Metric label="时间余量" value={time}/></div>
      <section className="battle-command__facts"><header><strong>现实输入 · 分层入账</strong><span><ShieldAlert size={13}/> AI 推演不能直接成为事实</span></header><div className="battle-command__fact-list">{facts.map((fact)=><p key={fact.id}><b>{fact.kind}</b>{fact.content}<small>来源 {fact.source} · 置信度 {fact.confidence} · 发生 {fact.occurredAt?.slice(0,16).replace("T"," ")??"未标注"} · 核验 {fact.verifiedAt?.slice(0,16).replace("T"," ")??"未核验"}</small></p>)}</div><div className="battle-command__fact-input"><select value={factKind} onChange={(e)=>{const next=e.target.value as BattleFact["kind"];setFactKind(next);if(next==="fact"&&factSource==="ai")setFactSource("user");}} aria-label="现实输入类型"><option value="fact">已核验事实</option><option value="assumption">假设</option><option value="unknown">未知变量</option><option value="goal">目标</option><option value="emotion">情绪信号</option></select><select value={factSource} onChange={(e)=>setFactSource(e.target.value as BattleFact["source"])} aria-label="现实输入来源"><option value="user">本人记录</option><option value="attachment">证据附件</option><option value="system">系统记录</option><option value="ai" disabled={factKind==="fact"}>AI 推断（仅假设）</option></select><input inputMode="numeric" min="0" max="100" value={factConfidence} onChange={(e)=>setFactConfidence(e.target.value)} aria-label="事实置信度" placeholder="置信度 0–100"/><input type="datetime-local" value={factOccurredAt} onChange={(e)=>setFactOccurredAt(e.target.value)} aria-label="发生时间"/><input type="datetime-local" value={factVerifiedAt} onChange={(e)=>setFactVerifiedAt(e.target.value)} aria-label="核验时间"/><input value={factText} onChange={(e)=>setFactText(e.target.value)} placeholder="输入事实、假设、未知、目标或情绪"/><button type="button" disabled={busy||!factText.trim()} onClick={()=>void addFact()}>入账</button></div></section>
      <ResourcePanel values={resources} setValues={setResources} runway={runway} time={time} busy={busy} save={saveResources}/><InventoryPanel battleId={battle.id} constraints={constraints} setConstraints={setConstraints} inventory={inventory} setInventory={setInventory} busy={busy} save={saveInventory}/><GravityPanel gravity={gravity}/><TimelinePanel timeline={timeline} edges={timelineEdges} draft={timelineDraft} setDraft={setTimelineDraft} busy={busy} add={addTimeline} link={linkTimeline}/><OpportunityPanel opportunities={opportunities} draft={opportunityDraft} setDraft={setOpportunityDraft} busy={busy} add={addOpportunity}/>
      {junctions.length>0?<section className="battle-command__junctions"><header><strong>现实交叉点</strong><span>时间 × 资源 × 风险</span></header><div>{junctions.map((junction)=><button type="button" key={junction.id} className={selectedJunction?.id===junction.id?"is-active":""} onClick={()=>void choose(junction)}><b>{junction.title}</b><small>{junction.description}</small><em>窗口 {junction.halfLifeAt?.slice(0,16).replace("T"," ")??"待定"}</em></button>)}</div></section>:<div className="battle-command__empty"><TimerReset size={22}/><strong>尚未扫描</strong><span>先补事实、底牌与红线，再扫描交叉点。</span></div>}</>}</section>
    <aside className="battle-command__right">{battle?<><div className="battle-command__eyebrow"><Crosshair size={14}/> ASYMMETRIC STRIKE CONSOLE</div><h3>{selectedJunction?.title??"等待一个交叉点"}</h3>{selectedJunction&&<p className="battle-command__junction-core">核心变量：{selectedJunction.coreVariable}</p>}<div className="battle-command__moves">{moves.map((move)=><MoveCard key={move.id} move={move} selected={selectedMove?.id===move.id} busy={busy} commit={commit}/>)}</div>{selectedMove&&<ExecutionPanel execution={execution} prepare={prepareExecution} save={saveExecution} update={updateAction} trigger={trigger} busy={busy}/>}<ReviewPanel draft={reviewDraft} setDraft={setReviewDraft} reviews={reviews} busy={busy} save={review}/>{moves.length===0&&<div className="battle-command__empty"><AlertTriangle size={20}/><span>扫描交叉点后，这里才会出现三手现实策略。</span></div>}</>:<div className="battle-command__empty"><Crosshair size={24}/><strong>推演台待命</strong><span>开局后，右侧只展示基于现实底牌的强攻、试局与对冲。</span></div>}</aside></section><BattleCopilotPanel accessToken={accessToken} canPersist={canPersist} battle={battle} guestCheckoutToken={guestCheckoutToken} guestUsageAvailable={guestUsageAvailable} accountUsageAvailable={accountUsageAvailable} onActivate={onLogin} battleId={battle?.id??null}/><BattleCollaborationPanel accessToken={accessToken} canPersist={canPersist} battleId={battle?.id??null}/><BattleStrategyArchive accessToken={accessToken} canPersist={canPersist} battleId={battle?.id??null}/><footer className="battle-command__status"><span>{status}</span><span>落子版本不可静默覆盖 · 现实事实优先 · 传统解释可关闭</span></footer></main>;
}

type IntakeStep = "situation" | "minimum" | "ideal" | "deadline" | "opponent";
const intakeSteps: Array<{key:IntakeStep;question:string;hint:string}> = [
  {key:"situation",question:"先不急着定义目标。现在到底发生了什么？这件事卡在哪里？",hint:"用自己的话说，乱一点也没有关系。"},
  {key:"minimum",question:"如果继续按现在的路径，最怕具体失去什么？",hint:"不知道就回答“不确定”，不要替自己编一个底线。"},
  {key:"ideal",question:"如果这一局打成了，你希望现实里出现什么可验证的变化？",hint:"别写“变好”；尽量说一个能观察到的结果。"},
  {key:"deadline",question:"最晚什么时候必须看到变化，或者必须做出选择？",hint:"不知道可以回答“不确定”，以后也能补。"},
  {key:"opponent",question:"谁、什么规则，或哪种资源限制，会把你拖回默认路径？",hint:"可以是人、组织、现金、时间、健康，或还没看清的变量。"},
];
const isUnknownAnswer=(value:string)=>/^(不知道|不确定|不清楚|没有|暂时没有|跳过|略过|无)$/i.test(value.trim());

function ConversationalIntake({draft,setDraft,busy,create}:{draft:Draft;setDraft:(value:Draft)=>void;busy:boolean;create:()=>void}){
  const [started,setStarted]=useState(false); const [step,setStep]=useState(0); const [answer,setAnswer]=useState(""); const [done,setDone]=useState(false);
  const [messages,setMessages]=useState<Array<{role:"agent"|"user";text:string}>>([]); const current=intakeSteps[step];
  const start=()=>{setStarted(true);setMessages([{role:"agent",text:intakeSteps[0].question}]);};
  const applyAnswer=(raw:string)=>{const text=raw.trim();if(!text||!current)return;const unknown=isUnknownAnswer(text);setMessages((rows)=>[...rows,{role:"user",text}]);if(current.key==="situation")setDraft({...draft,objective:unknown?"":text,title:draft.title||(!unknown?`${text.slice(0,24)}${text.length>24?"…":""}`:"")});if(current.key==="minimum")setDraft({...draft,minimumOutcome:unknown?"":text});if(current.key==="ideal")setDraft({...draft,idealOutcome:unknown?"":text});if(current.key==="opponent")setDraft({...draft,opponentSummary:unknown?"":text});setAnswer("");const next=step+1;if(next>=intakeSteps.length){setDone(true);setMessages((rows)=>[...rows,{role:"agent",text:"采访完成。没有答案的部分会保留在未知区；后续应靠事实、低成本试局与复盘收敛，而不是由系统替你猜。"}]);return;}setStep(next);setMessages((rows)=>[...rows,{role:"agent",text:intakeSteps[next].question}]);};
  return <section className="battle-command__intake"><div className="battle-command__eyebrow"><Target size={15}/> OPEN A BATTLE</div><h2>先把困局说出来，再决定要赢什么。</h2><p>你不需要一开始就知道底线和理想结果。推演台会和你一问一答，把模糊的困局整理成可行动的暂定战局。</p>{!started?<div className="battle-command__intake-start"><div><MessageCircle size={18}/><strong>战局采访</strong><span>约 5 个问题 · 可回答“不确定” · 不替你猜</span></div><button type="button" className="battle-command__primary" disabled={busy} onClick={start}>开始对话 <Send size={15}/></button></div>:<><div className="battle-command__dialogue" aria-live="polite">{messages.map((message,index)=><p key={`${message.role}-${index}`} className={`is-${message.role}`}><b>{message.role==="agent"?"推演台":"你"}</b><span>{message.text}</span></p>)}</div>{!done?<div className="battle-command__dialogue-input"><textarea autoFocus value={answer} onChange={(e)=>setAnswer(e.target.value)} onKeyDown={(e)=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();applyAnswer(answer);}}} placeholder={current?.hint} aria-label="回答推演台的问题"/><div><button type="button" disabled={!answer.trim()} onClick={()=>applyAnswer(answer)}>回答 <Send size={14}/></button><button type="button" onClick={()=>applyAnswer("不确定")}><SkipForward size={14}/> 暂不确定</button></div></div>:null}<div className="battle-command__intake-resolution"><header><strong>暂定战局</strong><span>{done?"对话完成":"对话中"}</span></header><label>战局名称<input value={draft.title} onChange={(e)=>setDraft({...draft,title:e.target.value})} placeholder="可稍后修改"/></label><div className="battle-command__resolution-grid"><Resolution label="眼下发生什么" value={draft.objective}/><Resolution label="输不起什么" value={draft.minimumOutcome}/><Resolution label="理想变化" value={draft.idealOutcome}/><Resolution label="对手 / 重力来源" value={draft.opponentSummary}/></div><label>硬期限（不知道可留空）<input type="datetime-local" value={draft.hardDeadline} onChange={(e)=>setDraft({...draft,hardDeadline:e.target.value})}/></label>{done?<button type="button" className="battle-command__primary" disabled={busy||!draft.title.trim()||!draft.objective.trim()} onClick={create}>建立暂定战局 <Crosshair size={15}/></button>:<p className="battle-command__resolution-note">完成采访后建立战局。任何空白都会明确标作“未确定”，不会被系统擅自补齐。</p>}</div></>}</section>;
}
function Resolution({label,value}:{label:string;value:string}){return <div className={`battle-command__resolution-item ${value.trim()?"is-known":"is-unknown"}`}><small>{label}</small><strong>{value.trim()||"未确定 · 后续通过事实与试局收敛"}</strong></div>}

function Metric({label,value}:{label:string;value:string}){return <article><small>{label}</small><strong>{value}</strong></article>}
function ResourcePanel({values,setValues,runway,time,busy,save}:{values:ResourceFields;setValues:(value:ResourceFields)=>void;runway:string;time:string;busy:boolean;save:()=>void}){const labels:{key:keyof ResourceFields;label:string}[]=[{key:"cashAvailable",label:"可支配现金"},{key:"monthlyFixedCost",label:"月固定支出"},{key:"monthlyNetCashflow",label:"月净现金流"},{key:"weeklyHoursAvailable",label:"每周可投入小时"},{key:"weeklyHoursCommitted",label:"已承诺小时"},{key:"consecutiveHighPressureDays",label:"连续高压天数"},{key:"maxHighPressureDays",label:"可承受高压上限"}];return <section className="battle-command__resources"><header><strong>冷酷底牌与资源跑道</strong><span>版本化快照 · 不靠感觉</span></header><div className="battle-command__resource-grid">{labels.map(({key,label})=><label key={key}>{label}<input inputMode="decimal" value={values[key]} onChange={(e)=>setValues({...values,[key]:e.target.value})}/></label>)}</div><p className="battle-command__resource-readout">现金跑道：{runway} · 时间余量：{time} · 高压：{values.consecutiveHighPressureDays||"未量化"}/{values.maxHighPressureDays||"未设上限"} 天</p><button type="button" disabled={busy} onClick={save}>锁定资源快照</button></section>}
function InventoryPanel({battleId,constraints,setConstraints,inventory,setInventory,busy,save}:{battleId:string;constraints:BattleConstraint[];setConstraints:(v:BattleConstraint[])=>void;inventory:InventoryItem[];setInventory:(v:InventoryItem[])=>void;busy:boolean;save:()=>void}){return <section className="battle-command__facts battle-command__facts--editable"><header><strong>硬约束 / 关键筹码</strong><button type="button" disabled={busy} onClick={save}>保存底牌与红线</button></header><div className="battle-command__editable-list"><div><b>红线</b>{constraints.map((item,index)=><label key={item.id}><input value={item.label} onChange={(e)=>setConstraints(constraints.map((row,i)=>i===index?{...row,label:e.target.value}:row))}/><small>{item.kind} · 严重度 {item.severity}</small></label>)}<button type="button" onClick={()=>setConstraints([...constraints,{id:`draft-${Date.now()}`,battleId,kind:"other",label:"",description:"",hard:true,severity:3,threshold:{},source:{}}])}>＋ 添加红线</button></div><div><b>筹码</b>{inventory.map((item,index)=><label key={item.id}><input value={item.label} onChange={(e)=>setInventory(inventory.map((row,i)=>i===index?{...row,label:e.target.value}:row))}/><small>{item.category} · {item.availability}</small></label>)}<button type="button" onClick={()=>setInventory([...inventory,{id:`draft-${Date.now()}`,battleId,category:"asset",label:"",description:"",quantity:null,unit:null,availability:"available",expiresAt:null,cost:{},evidence:{}}])}>＋ 添加筹码</button></div></div></section>}
function GravityPanel({gravity}:{gravity:GravityLine|null}){const scan=(gravity?.source?.oppositionScan as OppositionScan|undefined)??null;return <section className="battle-command__gravity"><header><strong>默认重力线 / 对手盘扫描</strong><span>{gravity?`基准置信度 ${gravity.confidence}/100`:"尚未生成"}</span></header>{gravity?<><p>{gravity.summary}</p><div className="battle-command__gravity-grid"><div><b>常规后果</b><span>{gravity.expectedOutcome}</span></div><div><b>不可变失败原因</b><span>{gravity.failureReasons.join("；")||"未记录"}</span></div>{scan?<><div><b>压力点</b><span>{scan.pressurePoints.join("；")||"尚未识别"}</span></div><div><b>可争杠杆</b><span>{scan.leverageOpenings.join("；")||"尚未识别"}</span></div><div><b>关键未知</b><span>{scan.unknowns.join("；")||"暂无"}</span></div><div><b>伦理边界</b><span>{scan.ethicalBoundary}</span></div></>:null}</div></>:<p>先补齐事实、底牌与红线，再扫描默认下坠线和对手盘。</p>}</section>}
function TimelinePanel({timeline,edges,draft,setDraft,busy,add,link}:{timeline:TimelineNode[];edges:TimelineEdge[];draft:{title:string;startsAt:string;kind:string;truthStatus:string};setDraft:(v:{title:string;startsAt:string;kind:string;truthStatus:string})=>void;busy:boolean;add:()=>void;link:(from:string,to:string,relation:string)=>void}){const [from,setFrom]=useState("");const [to,setTo]=useState("");const [relation,setRelation]=useState("causes");return <section className="battle-command__timeline"><header><strong>现实交叉沙盘</strong><span>事实与时间可跳转，推测不冒充因果</span></header><div className="battle-command__timeline-form"><input value={draft.title} onChange={(e)=>setDraft({...draft,title:e.target.value})} placeholder="过去发生了什么 / 未来验证什么"/><input type="datetime-local" value={draft.startsAt} onChange={(e)=>setDraft({...draft,startsAt:e.target.value})}/><select value={draft.kind} onChange={(e)=>setDraft({...draft,kind:e.target.value,truthStatus:e.target.value==="action"?"projected":e.target.value==="result"?"verified":"observed"})}><option value="fact">事实节点</option><option value="decision">已做选择</option><option value="risk">风险节点</option><option value="opportunity">机会节点</option><option value="action">未来行动</option><option value="result">验证结果</option></select><button type="button" disabled={busy||!draft.title.trim()} onClick={add}>入图</button></div>{timeline.length>1&&<div className="battle-command__timeline-link"><select value={from} onChange={(e)=>setFrom(e.target.value)}><option value="">起点</option>{timeline.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select><select value={relation} onChange={(e)=>setRelation(e.target.value)}><option value="causes">导致</option><option value="accelerates">加速</option><option value="blocks">阻断</option><option value="depends_on">依赖</option><option value="conflicts">冲突</option><option value="verifies">验证</option><option value="counterfactual">幽灵对照</option></select><select value={to} onChange={(e)=>setTo(e.target.value)}><option value="">终点</option>{timeline.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select><button type="button" disabled={busy||!from||!to||from===to} onClick={()=>link(from,to,relation)}>连线</button></div>}<div className="battle-command__timeline-nodes">{timeline.map((item)=><article key={item.id} className={`is-${item.truthStatus}`}><b>{item.title}</b><small>{item.startsAt?.slice(0,16).replace("T"," ")??"未定时间"} · {item.truthStatus}</small><em>{edges.filter((edge)=>edge.fromNodeId===item.id||edge.toNodeId===item.id).map((edge)=>edge.relation).join(" · ")}</em></article>)}</div></section>}
function OpportunityPanel({opportunities,draft,setDraft,busy,add}:{opportunities:Opportunity[];draft:{title:string;description:string;bestActionAt:string;closesAt:string;decayReason:string;missedCost:string};setDraft:(v:typeof draft)=>void;busy:boolean;add:()=>void}){return <section className="battle-command__opportunities"><header><strong>行动窗口雷达</strong><span>等一等，会具体失去什么</span></header><div className="battle-command__timeline-form"><input value={draft.title} onChange={(e)=>setDraft({...draft,title:e.target.value})} placeholder="窗口名称"/><input value={draft.description} onChange={(e)=>setDraft({...draft,description:e.target.value})} placeholder="机会描述 / 合法来源"/><input type="datetime-local" value={draft.bestActionAt} onChange={(e)=>setDraft({...draft,bestActionAt:e.target.value})} aria-label="最佳行动时间"/><input type="datetime-local" value={draft.closesAt} onChange={(e)=>setDraft({...draft,closesAt:e.target.value})} aria-label="关闭时间"/><input value={draft.decayReason} onChange={(e)=>setDraft({...draft,decayReason:e.target.value})} placeholder="衰减原因"/><input value={draft.missedCost} onChange={(e)=>setDraft({...draft,missedCost:e.target.value})} placeholder="错过后的物理代价"/><button type="button" disabled={busy||!draft.title.trim()||!draft.closesAt} onClick={add}>进雷达</button></div><div className="battle-command__timeline-nodes">{opportunities.map((item)=><article key={item.id}><b>{item.title}</b><small>{item.description||"无描述"} · 状态 {item.status}</small><small>最佳行动：{item.bestActionAt?.slice(0,16).replace("T"," ")??"未量化"} · 关闭：{item.closesAt?.slice(0,16).replace("T"," ")??"未量化"}</small><em>{String(item.decay.reason??"未记录")}；错过代价：{String(item.decay.missedCost??"未记录")}</em></article>)}</div></section>}
function MoveCard({move,selected,busy,commit}:{move:Move;selected:boolean;busy:boolean;commit:(move:Move)=>void}){const label=move.kind==="strong_attack"?"强攻手":move.kind==="probe"?"试局手":"对冲手";return <article className={`is-${move.kind}${selected?" is-selected":""}`}><header><span>{label}</span><small>{move.state}</small></header><h4>{move.title}</h4><p>{move.rationale}</p><dl><div><dt>关键变量</dt><dd>{move.keyVariable}</dd></div><div><dt>成本</dt><dd>{JSON.stringify(move.cost)}</dd></div><div><dt>上行 / 选择权</dt><dd>{JSON.stringify(move.upside)}</dd></div><div><dt>失败承伤</dt><dd>{JSON.stringify(move.failureCost)}</dd></div><div><dt>验证</dt><dd>{String(move.validation.successSignal??"待配置")} · 最晚 {String(move.validation.deadline??"未定")}</dd></div><div><dt>止损</dt><dd>{String(move.stop.condition??"待配置")} → {String(move.stop.action??"未配置")}</dd></div><div><dt>第一动作</dt><dd>{move.actions.map((action)=>`${action.title}（${action.owner||"执行人待定"}）`).join("；")||"未配置"}</dd></div></dl><button type="button" disabled={busy} onClick={()=>commit(move)}>{selected?"已落子":"落下这一子"}</button></article>}
function ExecutionPanel({execution,prepare,save,update,trigger,busy}:{execution:{actions:Action[];breakers:Breaker[]}|null;prepare:()=>void;save:()=>void;update:(v:Action)=>void;trigger:(v:Breaker)=>void;busy:boolean}){return <section className="battle-command__execution"><header><strong>落子执行台 / 不可静默覆盖</strong><button type="button" onClick={prepare}>从策略生成清单</button></header>{execution?<><div className="battle-command__action-list">{execution.actions.map((action,index)=><label key={action.id??index}><span>{index+1}. {action.title}</span><small>{action.owner||"执行人待定"} · {action.dueAt||"无期限"}</small><input className="battle-command__actual-cost" inputMode="decimal" defaultValue={typeof action.actualCost?.cash === "number"?String(action.actualCost.cash):""} placeholder="实际现金" aria-label={`${action.title} 实际现金`} onBlur={(e)=>void update({...action,actualCost:{...action.actualCost,cash:e.target.value===""?undefined:Number(e.target.value)}})}/><input className="battle-command__actual-cost" inputMode="decimal" defaultValue={typeof action.actualCost?.hours === "number"?String(action.actualCost.hours):""} placeholder="实际小时" aria-label={`${action.title} 实际小时`} onBlur={(e)=>void update({...action,actualCost:{...action.actualCost,hours:e.target.value===""?undefined:Number(e.target.value)}})}/><select value={action.status??"pending"} onChange={(e)=>void update({...action,status:e.target.value})}><option value="pending">待执行</option><option value="in_progress">进行中</option><option value="waiting">等待反馈</option><option value="done">已完成</option><option value="failed">失败</option><option value="skipped">跳过</option></select></label>)}</div><div className="battle-command__breaker-list"><b>风险断路器</b>{execution.breakers.map((item,index)=><p key={item.id??index}><strong>{item.label}</strong><span>{item.actionOnTrigger}</span>{item.triggeredAt?<em>已触发</em>:<button type="button" disabled={busy||!item.id} onClick={()=>trigger(item)}>触发并停止</button>}</p>)}</div><button type="button" className="battle-command__primary" disabled={busy} onClick={save}>保存执行令</button></>:<div className="battle-command__empty"><span>策略已锁定。先生成执行清单和至少一个断路器。</span></div>}</section>}
function ReviewPanel({draft,setDraft,reviews,busy,save}:{draft:{outcome:string;facts:string;whatChanged:string;nextAdjustment:string};setDraft:(v:typeof draft)=>void;reviews:Array<{id:string;outcome:string;nextAdjustment:string}>;busy:boolean;save:()=>void}){return <section className="battle-command__review"><header><strong>冷酷复盘</strong><span>{reviews.length} 次</span></header><textarea value={draft.outcome} onChange={(e)=>setDraft({...draft,outcome:e.target.value})} placeholder="实际发生了什么？"/><textarea value={draft.facts} onChange={(e)=>setDraft({...draft,facts:e.target.value})} placeholder="哪些事实改变了？"/><textarea value={draft.nextAdjustment} onChange={(e)=>setDraft({...draft,nextAdjustment:e.target.value})} placeholder="下一局要修正哪条规则？"/><button type="button" disabled={busy||!draft.outcome.trim()} onClick={save}>入档复盘</button>{reviews.map((item)=><p key={item.id}><b>{item.outcome}</b><span>{item.nextAdjustment}</span></p>)}</section>}
