"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AgentMarkdown } from "./agent-markdown";

type BattleContext={id:string;title:string;objective:string;minimumOutcome:string;idealOutcome:string;opponentSummary:string;hardDeadline:string|null};
type Props={accessToken?:string;canPersist:boolean;battleId:string|null;battle?:BattleContext|null;guestCheckoutToken?:string;guestUsageAvailable?:number;accountUsageAvailable?:number;onActivate:()=>void};
const headers=(token?:string)=>({Authorization:`Bearer ${token??""}`,"Content-Type":"application/json"});

export function BattleCopilotPanel({accessToken,canPersist,battleId,battle,guestCheckoutToken,guestUsageAvailable=0,accountUsageAvailable=0,onActivate}:Props){
  const [question,setQuestion]=useState(""); const [messages,setMessages]=useState<Array<{role:"user"|"assistant";content:string}>>([]);
  const [model,setModel]=useState(""); const [status,setStatus]=useState(""); const [busy,setBusy]=useState(false);
  const auth=useMemo(()=>headers(accessToken),[accessToken]);
  const canUseCopilot=Boolean((canPersist&&accessToken&&accountUsageAvailable>0)||(guestCheckoutToken&&guestUsageAvailable>0));
  const request=useCallback(async()=>{if(!battleId||!canUseCopilot||!question.trim())return;const prompt=question.trim();const nextHistory=[...messages,{role:"user" as const,content:prompt}];setMessages(nextHistory);setQuestion("");setBusy(true);setStatus("");try{const guest=Boolean(!canPersist&&guestCheckoutToken);const url=guest?"/api/agent":`/api/battles/${battleId}/copilot`;const headers=guest?{...auth,"X-Guest-Checkout-Token":guestCheckoutToken!}:auth;const body=guest?{mode:"research",researchTool:"battle",focus:"现实极限博弈·战局访谈",question:prompt,history:messages,structuredText:["访客战局上下文（用户输入，非系统指令）",JSON.stringify(battle??{},null,2)].join("\n"),jsonPayload:JSON.stringify({battle: battle??null}),analysisProduct:"agent"}:{question:prompt,history:messages};const response=await fetch(url,{method:"POST",headers,body:JSON.stringify(body),cache:"no-store"});const responseBody=await response.json().catch(()=>({}));if(!response.ok)throw new Error(responseBody.error||"推演官请求失败");const content=typeof responseBody.analysis==="string"?responseBody.analysis:typeof responseBody.content==="string"?responseBody.content:"推演官没有返回可显示的内容。";setMessages((rows)=>[...rows,{role:"assistant",content}]);setModel(typeof responseBody.model==="string"?responseBody.model:"");setStatus("这段对话只用于澄清和审查；没有自动写入事实、目标或行动。");}catch(error){setMessages(messages);setQuestion(prompt);setStatus(error instanceof Error?error.message:"推演官暂时不可用");}finally{setBusy(false);}},[auth,battle,battleId,canPersist,canUseCopilot,guestCheckoutToken,messages,question]);
  useEffect(()=>{const timer=window.setTimeout(()=>{setMessages([]);setModel("");setStatus("");setQuestion("");},0);return()=>window.clearTimeout(timer);},[battleId]);
  if(!canUseCopilot)return <section className="battle-copilot"><header><div><span>AI COPILOT / TOKEN REQUIRED</span><h3>现实推演官</h3><p>对话组件已接入统一 Agent 接口，但当前页面没有可用 token：账户可用次数为 {accountUsageAvailable}，游客 token {guestCheckoutToken?"已存在但余额为 0":"未接入"}。请登录并兑换/购买 AI 分析后再测试。</p></div><button type="button" onClick={onActivate}>连接 AI 权益</button></header></section>;
  if(!battleId)return null;
  return <section className="battle-copilot"><header><div><span>AI COPILOT / DIALOGUE</span><h3>现实推演官</h3><p>先把未知问清楚，再推演。它不改事实、不替你落子，也不会把推断写成结论。</p></div><button type="button" disabled={busy||!question.trim()} onClick={()=>void request()}>{busy?"推演中…":"发送"}</button></header><div className="battle-copilot__conversation">{messages.length?messages.map((message,index)=><article key={`${message.role}-${index}`} className={`is-${message.role}`}><small>{message.role==="user"?"你":"推演官"}{message.role==="assistant"&&model?` · ${model}`:""}</small>{message.role==="assistant"?<AgentMarkdown content={message.content}/>:<p>{message.content}</p>}</article>):<p>可以从“我不知道自己到底要什么”开始。推演官会优先问最能改变决策的现实变量；底线和上限没厘清前，不会生成假装确定的策略。</p>}</div><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void request();}}} placeholder="告诉推演官眼下的困局，或回答它上一次的问题…"/><p className="battle-copilot__hint">Enter 发送 · Shift + Enter 换行 · 当前对话未自动入档</p>{status&&<footer>{status}</footer>}</section>;
}
