import { NextResponse } from "next/server";
import { AccountSubjectError, requireAccountSubject } from "@/lib/agent/account-subject";
import { asRecord, asText, isUuid } from "@/lib/battle/input";
import { acceptCollaboratorInvitation, listCollaborators, setCollaboratorStatus, upsertCollaborator } from "@/lib/battle/extended-repository";
import { COLLABORATOR_ROLES } from "@/lib/battle/types";
type Context={params:Promise<{id:string}>};
const statuses=["invited","active","revoked"] as const;
export async function GET(request:Request,context:Context){try{const id=(await context.params).id;if(!isUuid(id))return NextResponse.json({error:"战局标识无效。"},{status:400});const value=await listCollaborators(await requireAccountSubject(request),id);return value===null?NextResponse.json({error:"只有战局所有者可查看协作者。"},{status:403}):NextResponse.json({collaborators:value});}catch(error){return error instanceof AccountSubjectError?NextResponse.json({error:error.message},{status:error.status}):NextResponse.json({error:"读取协作者失败。"},{status:500});}}
export async function POST(request:Request,context:Context){try{const id=(await context.params).id;if(!isUuid(id))return NextResponse.json({error:"战局标识无效。"},{status:400});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const subjectType=asText(body?.subjectType,32);const subjectId=asText(body?.subjectId,128);const role=body?.role; if(!subjectType||!subjectId||typeof role!=="string"||!COLLABORATOR_ROLES.includes(role as never)||role==="owner")return NextResponse.json({error:"协作者身份或角色无效。"},{status:400});const value=await upsertCollaborator(await requireAccountSubject(request),id,{subjectType,subjectId,role:role as never,permissions:asRecord(body?.permissions)??{}});return value===null?NextResponse.json({error:"只有战局所有者可邀请协作者。"},{status:403}):NextResponse.json({collaborator:value},{status:201});}catch(error){return error instanceof AccountSubjectError?NextResponse.json({error:error.message},{status:error.status}):NextResponse.json({error:"邀请协作者失败。"},{status:500});}}
export async function PATCH(request:Request,context:Context){try{const id=(await context.params).id;if(!isUuid(id))return NextResponse.json({error:"战局标识无效。"},{status:400});const body=await request.json().catch(()=>null) as {collaboratorId?:unknown;status?:unknown;action?:unknown}|null;if(!isUuid(body?.collaboratorId))return NextResponse.json({error:"协作者标识无效。"},{status:400});const subject=await requireAccountSubject(request);if(body.action==="accept"){const accepted=await acceptCollaboratorInvitation(subject,id,body.collaboratorId);return accepted?NextResponse.json({collaborator:accepted}):NextResponse.json({error:"没有可接受的协作邀请。"},{status:404});}if(typeof body?.status!=="string"||!statuses.includes(body.status as never))return NextResponse.json({error:"协作者状态无效。"},{status:400});const value=await setCollaboratorStatus(subject,id,body.collaboratorId,body.status as never);return value===null?NextResponse.json({error:"只有战局所有者可管理协作者。"},{status:403}):value===undefined?NextResponse.json({error:"协作者不存在。"},{status:404}):NextResponse.json({collaborator:value});}catch(error){return error instanceof AccountSubjectError?NextResponse.json({error:error.message},{status:error.status}):NextResponse.json({error:"更新协作者失败。"},{status:500});}}
